# Generated by Django 4.2 on 2025-02-28 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantTaskFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('W', 'Watered'), ('F', 'Fertilized'), ('R', 'Repotted'), ('V', 'Given vitamins'), ('I', 'Treated with insecticide')], max_length=20)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_care.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantGraveyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField(auto_now_add=True)),
                ('cause_of_death', models.CharField(blank=True, choices=[('overwatering', 'Overwatering'), ('underwatering', 'Underwatering'), ('pest_infestation', 'Pest Infestation'), ('lack_of_light', 'Lack of light'), ('too_much_light', 'Too much light'), ('nutrient_deficiency', 'Nutrient Deficiency'), ('unknown', 'Unknown')], default='unknown', max_length=50, null=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_care.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('W', 'Watered'), ('F', 'Fertilized'), ('R', 'Repotted'), ('V', 'Given vitamins'), ('I', 'Treated with insecticide')], max_length=20)),
                ('task_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_care.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_care.plantgroup'),
        ),
    ]
