# Generated by Django 4.2 on 2025-03-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='plant_care.plantgroup'),
        ),
    ]
