# Generated by Django 4.2 on 2025-03-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0002_alter_plant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcarehistory',
            name='task_type',
            field=models.CharField(choices=[('Watering', 'watered'), ('Fertilizing', 'fertilized'), ('Repotting', 'repotted'), ('Vitamin treatment', 'given vitamins'), ('Insecticide treatment', 'treated with insecticide')], max_length=25),
        ),
        migrations.AlterField(
            model_name='planttaskfrequency',
            name='task_type',
            field=models.CharField(choices=[('Watering', 'watered'), ('Fertilizing', 'fertilized'), ('Repotting', 'repotted'), ('Vitamin treatment', 'given vitamins'), ('Insecticide treatment', 'treated with insecticide')], max_length=25),
        ),
    ]
