# Generated by Django 4.2 on 2025-03-06 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0004_alter_planttaskfrequency_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
