# Generated by Django 4.2 on 2025-03-06 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0005_alter_plant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcarehistory',
            name='task_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
