# Generated by Django 4.2 on 2025-03-09 18:14

from django.db import migrations, models
import plant_care.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_care', '0006_alter_plantcarehistory_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, validators=[plant_care.models.validate_plant_unique_name]),
        ),
    ]
